services:
  - type: web
    name: sustainableecommerce
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn sustainableecommerce.wsgi"
    envVars:
      - key: DEBUG
        value: 'False'
